### ISSUE TITLE
XML formating issues with Xteve

### ISSUE THREAD

**Issue by GameEnder** [chris102994/docker-toonamiaftermath#14]
Xteve is having issues for me for me when I import the EPG xml file. It will read the channel id as the display name and then get stuck in a crash loop requiring a restore from a backup to clear it out to stop the crashing. Would it be posilbe to add a option for instead of channel id's the xml and instead have the display name of the channel? Most other xml EPG's that I use have it that way and don't crash xteve.

**Comment by chris102994** [comment]
I'm unsure I understand what your issue is or what you're suggesting with the way this is worded. So in the XMLTV generated we have

```xml
<channel id="1">
    <display-name lang="en">Toonami Aftermath EST</display-name>
    <icon src="https://imgur.com/NkYPoLH.png"/>
    <url>http://api.toonamiaftermath.com:3000/est/playlist.m3u8?useHttps=true</url>
</channel>
...
```

Based on the official [XMLTV DTD Spec](https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd#L208) It says:

> Each channel has one id attribute, which must be unique and should
preferably be in the form suggested by RFC2838 (the 'broadcast'
element of the grammar in that RFC, in other words, a DNS-like name
but without any URI scheme).  Then one or more display names which are
shown to the user.  You might want a different display name for
different languages, but also you can have more than one name for the
same language.  Names listed earlier are considered 'more canonical'.

And then has an [example](https://github.com/AlekSi/xmltv/blob/master/example.xml#L5) of:
```xml
 <channel id="I10436.labs.zap2it.com">
    <display-name>13 KERA</display-name>
    <display-name>13 KERA TX42822:-</display-name>
    <display-name>13</display-name>
    <display-name>13 KERA fcc</display-name>
    <display-name>KERA</display-name>
    <display-name>KERA</display-name>
    <display-name>PBS Affiliate</display-name>
    <icon src="file://C:\Perl\site/share/xmltv/icons/KERA.gif" />
  </channel>
```

While it's true it isn't a "DNS Like Name" (which seems to be a suggestion not a regulation). Since I do not actively work on the project any more (I just share it since it's worked stable for years on my use-case) I don't think this warrants a change since it's not actually something imposed by the XMLTV spec - this more so seems to be an issue with Xteve - hence why I moved away from the project (that and Emby just supports remapping and reading from spec perfectly).

You have 2 options going forward if you wish to work around the issues with xteve.

1. Fork this repo and make the changes from #1 and re-build for yourself
2. (These will be multi-line instructions)
    a. Copy this file locally: https://github.com/chris102994/docker-toonamiaftermath/blob/master/rootfs/app/ToonamiAftermath/ToonamiAftermath/data/channels.xml
    b. Modify the `root.element.[*].id` element's how you'd like
    c. Mount it into your container at `/app/ToonamiAftermath/ToonamiAftermath/data/channels.xml` with a flag like `-v /path/to/channels.xml:/app/ToonamiAftermath/ToonamiAftermath/data/channels.xml:z` (I believe the `z` flag will work).
    
    
With that being said - I wrote and built this in the early days of programming/devops and it's not exactly beautifully written/built. I will likely do a re-write of it in the future with a common core of different scrapers I've built.

**Comment by GameEnder** [comment]
Thanks for explaining. Was not expecting you to answer so quickly.

The second example:

` <channel id="I10436.labs.zap2it.com">
    <display-name>13 KERA</display-name>
    <display-name>13 KERA TX42822:-</display-name>
    <display-name>13</display-name>
    <display-name>13 KERA fcc</display-name>
    <display-name>KERA</display-name>
    <display-name>KERA</display-name>
    <display-name>PBS Affiliate</display-name>
    <icon src="file://C:\Perl\site/share/xmltv/icons/KERA.gif" />
  </channel>`

That is the output I was hoping you could give a opting for that would work around xteve's issues.

 I was actually looking at migrating away from xteve as it seems to get bugger by the day and is not updated anymore.

https://github.com/SenexCrenshaw/StreamMaster is a option that seems to be in active development will probably migrate there.

**Comment by GameEnder** [comment]
I use Plex. Is how I found xteve originally for its homerun emulation. Is also why I was looking at Stream Master as it also has Homerun emulation.

**Comment by chris102994** [comment]
Well good luck and I hope it works for you if/when you do migrate. Hope the instructions I provided get you buy in the meantime.
